= I found a really cool website!

I made a poll on https://twitter.com/zelafary[Twitter] to see if anyone wanted to read a blog post about a website I found. 2 people voted yes.

So here it is.

=== http://apollo17.org[Apollo 17]

I'm so glad I found this. I love space, so much. And this has the 3 day stay on the moon in real time! There's photos, transcripts, guided tour, videos and a time-line! It's amazing!

The whole thing would take approximately 15 days to watch from start to finish. It would be awesome to get a second computer or something, plug it into a monitor. And then just leave it there. But I don't have enough computers to do that. But I do put it on every now and then and leave it there.

There's 2 guys that worked on this, gathered information from the internet and audio clips and everything and stitched it together. Took them years! You can read more about the project http://benfeist.com/project-apollo-17/[here].

I think it's a bit calming to watch, and exciting. I wonder how it felt like in '72 when people watched this on television. Would probably be amazing.

If you have a few days to spare, or just want to have something to watch. Go to http://apollo17.org and watch it. It's interesting and exciting and if you love space, I guarantee you that you will love this too.