= When your stomach hurts
:published_at: 2016-07-06

I've had some small problems with my stomach before. Probably due to stress but when you don't eat much for a long while your stomach gets a bit more empty then usual. When you then eat something really bad and you vomit you practicly make it completely empty... I think this is what happened to me, after I vomited I were scared to eat because of the fear of it happening again. So I believe my acid levels got higher and higher and now I've had abdominal pains for almost 4 weeks. I feel a piercing constant hurting feeling as well as nausea on the mornings and then before I go to bed I feel a strong nasuea feeling. It's horrible to say the least... How do I solve this?

I went to the doctor a few days ago and I told her about my problem. She then told me to try to get some medication that reduces the acid levels in my stomach. So I did that and now I take those when I wake up and around dinner time. I also force myself to eat, at first I only ate yogurt and ["Filmjölk"](http://en.wikipedia.org/wiki/Filmj%C3%B6lk" target="_blank). It started out okay then my stomach got kinda "loose" but I only ate that for about 2 days, small portions every now and then when I started to feel nauseated.

It has gotten better and I do feel better when I eat, so the reason explained above is probably the cause of why I've been feeling like this for such a long time... It was just stupid of me that I didn't eat anything propperly for around 3 weeks and didn't do anything about it straight away.

I hope that I will feel better soon and that I can do continue to work on my project because now, my stomach hurts to the point that I'm scared of going out because I constantly think "What if I vomit?" so I've been staying inside eating small portions of food for a few days now and hopefully it will be better soon.
