= School related problems
:published_at: 2016-09-14


Problems can cause alot of extra work and make you really tired. So when the town denies your request to pay for residential at a school... You don't get much to do. Go up play games or watch a movie, eat and then do that throughout the day and then go to bed... Repeat.... This gets boring after a few days... But after a few weeks it gets repetative and it's driving me nuts.

I'm starting to have nightmares at nights... Might not be connected to me not able to go to school, but I'm sitting at home all day long doing practicly nothing... I watched 3 harry potter movies in 1 sitting *in order*. Life is getting boring and I don't have much to do. I feel like I should go do something but what is there to do? I'm soon 16 and I "go" to "gymnasiet", think of it as high school or college if you wish. It's a town away and I had problems taking the bus to a school inside my town already so I'm gonna have even more problems going to there. It's a 10 minute bus ride, 30 minute train ride and a 30 minute walk. It's alot and I just can't handle that. The fear of being lost or taking the wrong train is just killing me. Either way, we decided to do an appeal against the decition to not pay it and now that's in the work.

In the mean time I just got to pull through. I should start doing walks again... Maybe around 11:00 AM and then another one at 3:00 PM that should keep me energized and maybe even happier. I'm writing this at 8:30 roughly so I guess I'll go have some breakfast and then I'll prepare for a walk.

Thanks for reading I hope I'll get to migrate the blog to a propper website soon.
